/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-04-02 08:01:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.corpPage.individual.center;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class deleteDealCheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Yeob's/Desktop/eclipse/Spring_Works/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/aaa/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1487668142835L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/aaa/resources/js/yeob/httpRequest.js\"></script>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"60168\",secure:\"60173\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-42\" data-genuitec-path=\"/aaa/src/main/webapp/WEB-INF/views/corpPage/individual/center/deleteDealCheck.jsp\">\r\n");
      out.write("\t<br data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-42\" data-genuitec-path=\"/aaa/src/main/webapp/WEB-INF/views/corpPage/individual/center/deleteDealCheck.jsp\">\r\n");
      out.write("\t<div style=\"width: 450px;\">\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<legend style=\"font-size: large; border: 0px solid white;\"><strong>딜 삭제를 위한 인증절차</strong></legend>\r\n");
      out.write("\t\t\t\t<div style=\"font-size: small;\">비밀번호를 입력해주세요</div><br>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: left;\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span style=\"margin-left: 70px;\">회사 이름 </span>\r\n");
      out.write("\t\t\t\t\t\t<span style=\"margin-left: 35px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ corpLogin.getC_name() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span style=\"margin-left: 70px;\">비밀 번호 </span>\r\n");
      out.write("\t\t\t\t\t\t<span style=\"margin-left: 30px;\"><input type=\"password\" id=\"corpPassword\" \r\n");
      out.write("\t\t\t\t\t\t\tautocomplete=\"off\" placeholder=\"비밀번호를 입력하세요\"><br></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<p align=\"center\" style=\"margin-left: -60px;\">&nbsp;\r\n");
      out.write("\t\t<button onclick=\"pwCheck('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ di_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"\r\n");
      out.write("\t\t\tstyle=\"cursor: pointer; \r\n");
      out.write("\t\t\t\tbackground-color: #FFDF32; \r\n");
      out.write("\t\t\t\twidth: 180px;\r\n");
      out.write("\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t\tcolor: black; \r\n");
      out.write("\t\t\t\tfont-size: large;\"><strong>삭제하기</strong></button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<button onclick=\"closePop()\"\r\n");
      out.write("\t\t\tstyle=\"cursor: pointer; \r\n");
      out.write("\t\t\t\tborder: 1px solid #A8A8A9;\r\n");
      out.write("\t\t\t\twidth: 180px;\r\n");
      out.write("\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t\tcolor: black;\r\n");
      out.write("\t\t\t\tfont-size: large;\"><strong>취소하기</strong></button>&nbsp;\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction pwCheck(di_num) {\r\n");
      out.write("\t\t\tif(document.getElementById(\"corpPassword\").value != \"\") {\r\n");
      out.write("\t\t\t\tvar pwCheck = document.getElementById(\"corpPassword\").value;\r\n");
      out.write("\t\t\t\tvar params = \"c_pw=\"+pwCheck+\"&di_num=\"+di_num;\r\n");
      out.write("\t\t\t\tsendRequest(\"/aaa/idvCorp/dealDeleteOk\", params, deleteCheck, \"post\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"corpPassword\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction deleteCheck() {\r\n");
      out.write("\t\t\tif(httpRequest.readyState == 4) {\r\n");
      out.write("\t\t\t\tif(httpRequest.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar rcvData = httpRequest.responseText;\r\n");
      out.write("\t\t\t\t\tif(rcvData == \"정삭적으로 삭제되었습니다.\") {\r\n");
      out.write("\t\t\t\t\t\topener.location.href=\"/aaa/idvCorp/dealDelete\";\r\n");
      out.write("\t\t\t\t\t\tself.close();\r\n");
      out.write("\t\t\t\t\t} else if(rcvData == \"비밀번호가 일치하지 않습니다.\") {\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"corpPassword\").value=\"\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"corpPassword\").focus();\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(rcvData);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"*** 실패 : \" + httpRequest.status);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction closePop() {\r\n");
      out.write("\t\t\tself.close();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
