/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-04-06 09:40:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.yeob.bottom;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bottomPop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Yeob's/Desktop/eclipse/Spring_Works/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/aaa/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1487668142835L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("        <title>이니페이 에스크로 가입사실 확인</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/aaa/resources/css/yeob/aaa.css\" />\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        <!--\r\n");
      out.write("            function MM_preloadImages() { //v3.0\r\n");
      out.write("                var d = document;\r\n");
      out.write("                if (d.images) {\r\n");
      out.write("                    if (!d.MM_p)\r\n");
      out.write("                        d.MM_p = new Array();\r\n");
      out.write("                    var i, j = d.MM_p.length, a = MM_preloadImages.arguments;\r\n");
      out.write("                    for (i = 0; i < a.length; i++)\r\n");
      out.write("                        if (a[i].indexOf(\"#\") != 0) {\r\n");
      out.write("                            d.MM_p[j] = new Image;\r\n");
      out.write("                            d.MM_p[j++].src = a[i];\r\n");
      out.write("                        }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        //-->\r\n");
      out.write("        </script>\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("            <!--\r\n");
      out.write("            @charset \"utf-8\";\r\n");
      out.write("            /* CSS Document */\r\n");
      out.write("\r\n");
      out.write("            /* Common */ \r\n");
      out.write("            html,body{height:auto;margin:0;padding:0;border:0;font-family:dotum,'돋움',Helvetica,sans-serif;font-size:12px;color:#585858;line-height:1.5;text-align:left;} \r\n");
      out.write("            h1, h2, h3, h4, h5, h6, h7 {font-size:1em; margin:0;}\r\n");
      out.write("            address, em, strong { font-style:normal;}\r\n");
      out.write("            img, fieldset, form {border:0 none; margin:0; padding:0; vertical-align:middle;}\r\n");
      out.write("            input, select, button {vertical-align:middle; margin:0; padding:0;}\r\n");
      out.write("            legend, .hide { overflow:hidden; position:absolute; top:0; left:0; font-size:1%; line-height:1%;}\r\n");
      out.write("            hr {visibility:hidden;overflow:hidden;position:absolute;top:0;left:0;width:1px;height:1px;font-size:0;line-height:0}\r\n");
      out.write("            img {border:0;}\r\n");
      out.write("            ul,ol,dl{list-style:none;}\r\n");
      out.write("            ul,ol,dl,li,dt,dd,p{margin:0; padding:0}\r\n");
      out.write("            input, textarea, select {font-family:Gulim,'굴림',Helvetica,sans-serif;font-size:12px;color:#585858;line-height:1.5;text-align:left;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            a:link,a:active,a:visited{color:#585858;text-decoration:none}\r\n");
      out.write("            a:hover,a:focus{color:#92278f;font-weight:normal;text-decoration:underline}\r\n");
      out.write("\r\n");
      out.write("            .ac {text-align:center;}\r\n");
      out.write("\r\n");
      out.write("            /* 팝업 */\r\n");
      out.write("            #pop_wrapper {position:relative;}\r\n");
      out.write("            #pop_wrapper h1 {height:102px; background:url(images/popup/bg_header.gif) repeat-x; padding-left:32px;}\r\n");
      out.write("            #pop_wrapper h1 img {margin-top:23px;}\r\n");
      out.write("            #pop_wrapper .pop_cont {padding:25px 40px 20px; padding-left:40px; padding-right:40px;  color:#585858;}\r\n");
      out.write("            #pop_wrapper .pop_cont .pop_summary {margin-top:-3px; margin-bottom:33px;} \r\n");
      out.write("\r\n");
      out.write("            #pop_wrapper .payment_time .state {position:absolute; top:68px; right:30px;}\r\n");
      out.write("            #pop_wrapper .payment_time .time {position:absolute; top:25px; right:30px; color:#fff;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            .security_util {background:url(http://image.inicis.com/mkt/certmark/escrow/escrow_74x74_color.png) no-repeat; padding-left:105px; display:table-cell; height:81px; vertical-align:middle; *padding-top:15px; *margin-bottom:-15px;}\r\n");
      out.write("            .security_util2 {background:url(http://image.inicis.com/mkt/certmark/escrow/escrow_74x74_color.png) no-repeat; padding-left:105px; display:table-cell; height:81px; vertical-align:middle; *padding-top:5px; *margin-bottom:-5px;}\r\n");
      out.write("            .security_info {background:url(images/popup/bg_info_lst.gif) repeat-y; border-top:1px solid #912790; margin-top:28px;}\r\n");
      out.write("            .security_info dl {overflow:hidden;}\r\n");
      out.write("            .security_info dl dt {float:left; width:130px; margin-right:10px; padding:11px 0 9px 15px; color:#444; font-weight:bold; border-bottom:1px solid #e6e6e6;}\r\n");
      out.write("            .security_info dl dd {border-bottom:1px solid #e6e6e6; padding:11px 0 9px;margin-left: 155px;}\r\n");
      out.write("            .security_info table {overflow:hidden;}\r\n");
      out.write("            .security_info .tit {font-weight:bold;padding:11px 0 9px 15px;border-bottom:1px solid #e6e6e6;}\r\n");
      out.write("            .security_info .cont {border-bottom:1px solid #e6e6e6; padding:11px 0 9px;margin-left: 155px;}\r\n");
      out.write("            .security_note {padding-top:22px;}\r\n");
      out.write("            .security_note p {padding-top:10px;}\r\n");
      out.write("            .security_note p a {text-decoration:underline; color:#585858; font-weight:bold;}\r\n");
      out.write("\r\n");
      out.write("            .btn.vtxt {margin-top:30px; height:29px; display:inline-block;}\r\n");
      out.write("            .btn.vtxt a {display:block; height:29px; background:#90278e; padding:0 28px; line-height:29px; font-size:12px; color:#fff !important; font-weight:bold;}\r\n");
      out.write("\r\n");
      out.write("            -->\r\n");
      out.write("        </style>\r\n");
      out.write("    <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"60168\",secure:\"60173\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("    <body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-131\" data-genuitec-path=\"/aaa/src/main/webapp/WEB-INF/views/yeob/bottom/bottomPop.jsp\">\r\n");
      out.write("            <div id=\"pop_wrapper\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-131\" data-genuitec-path=\"/aaa/src/main/webapp/WEB-INF/views/yeob/bottom/bottomPop.jsp\">\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("                <!-- HEADER --> \r\n");
      out.write("                <div style=\"background-color: #4A1F74\"><h1><img src=\"https://mark.inicis.com/mark/images/popup/h1_inisis_accout.gif\" alt=\"이니페이 에스크로 가입사실 확인\"></h1></div>\r\n");
      out.write("                <!-- //HEADER --> \r\n");
      out.write("                <div class=\"payment_time\" style=\"background-color: #371756\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                    <p class=\"state\" ><img src=\"https://mark.inicis.com/mark/images/popup/kg_security.gif\" alt=\"결제보안 작동 중\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- CONTAINER --> \r\n");
      out.write("                <div id=\"pop_container\"> \r\n");
      out.write("                    <div class=\"pop_cont\">\r\n");
      out.write("                        <!-- pop content -->\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"security_util2\">\r\n");
      out.write("                            아래와 같이 <strong><a href=\"#\" target=\"_blank\" class=\"service_link\">www.dasam.com</a></strong>은 (주)이니시스의 결제대금 예치서비스인 이니페이 에스크로의 이용사용자로 등록하여 에스크로 서비스를 제공하고 있으며, 귀하의 결제 정보의 보안이 최상의 상태로 유지되고 있습니다. \r\n");
      out.write("                            <br/><b>결제대금예치업 등록번호 : 02-006-00013</b>\r\n");
      out.write("                        </p> <!-- //1129 : 수정 -->\r\n");
      out.write("                        <div class=\"security_info\">\t\r\n");
      out.write("                            <!-- \t \r\n");
      out.write("                                    <dl>\r\n");
      out.write("                                            <dt>상호</dt>\r\n");
      out.write("                                            <dd></dd>\r\n");
      out.write("                                            <dt>URL</dt>\r\n");
      out.write("                                            <dd></dd>\r\n");
      out.write("                                            <dt>사용결제수단</dt>\r\n");
      out.write("                                            <dd></dd>\r\n");
      out.write("                                            <dt>에스크로 결제수단</dt>\r\n");
      out.write("                                            <dd></dd>\r\n");
      out.write("                                            <dt>인증상태</dt>\r\n");
      out.write("                                            <dd>        ( ~ )\r\n");
      out.write("                            </dd>\r\n");
      out.write("                                            \r\n");
      out.write("                                    </dl>\r\n");
      out.write("                            -->\r\n");
      out.write("                            <table>\r\n");
      out.write("                                <colgroup>\r\n");
      out.write("                                    <col width=\"150\"></col>\r\n");
      out.write("                                    <col width=\"*\"></col>\r\n");
      out.write("                                </colgroup>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"tit\">상호</td>\r\n");
      out.write("                                    <td class=\"cont\">다삼</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"tit\">사업자번호</td>\r\n");
      out.write("                                    <td class=\"cont\">9019197513</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"tit\">URL</td>\r\n");
      out.write("                                    <td class=\"cont\">www.dasam.com</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <!-- \r\n");
      out.write("                                <tr>\r\n");
      out.write("                                        <td class=\"tit\">사용결제수단</td>\r\n");
      out.write("                                        <td class=\"cont\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                -->\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"tit\">에스크로 결제수단</td>\r\n");
      out.write("                                    <td class=\"cont\">실시간계좌이체,가상계좌</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"tit\">인증상태</dt>\r\n");
      out.write("                                        <td class=\"cont\">\r\n");
      out.write("                                            <!-- 20141205, 인증상태 수정 by 이현욱 -->\r\n");
      out.write("                                            인증 (2016-09-12 ~ 2017-09-11)\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>             \r\n");
      out.write("                        </div>  \r\n");
      out.write("                        <div class=\"security_note\">\r\n");
      out.write("                            이니시스 결제 인증마크는 전자결제 No.1 이니시스의 심사를 통과하여 이니시스의 결제 시스템을 탑재한 가맹점만이 이용할 수 있습니다.\t\t\t\t\r\n");
      out.write("                            <p><a href=\"#\">[이니시스의 결제 시스템의 특징 자세히 보기]</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"btn_wrap ac\">\r\n");
      out.write("                            <span class=\"btn vtxt\"><a href=\"#\" onclick=\"window.close();\r\n");
      out.write("                                            return false;\">닫기</a></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- //pop content -->\r\n");
      out.write("                    </div> \r\n");
      out.write("                </div> \r\n");
      out.write("                <!-- //CONTAINER -->  \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 중지나 해지 일때 -->\r\n");
      out.write("        <!-- 중지나 해지 일때 -->\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("        </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
