/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-04-01 12:01:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.adminPage.top;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class topIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Yeob's/Desktop/eclipse/Spring_Works/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/aaa/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1487668142835L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- \t<meta name=\"refresh\"> -->\r\n");
      out.write("<!-- \t<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script> -->\r\n");
      out.write("<!-- \t<script type=\"text/javascript\" src=\"/aaa/resources/js/yeob/aa/jquery.easing.js\"></script> -->\r\n");
      out.write("<!-- \t<script type=\"text/javascript\" src=\"/aaa/resources/js/yeob/aa/jquery.rollingCounter.min.js\"></script> -->\r\n");
      out.write("\t<title>Yoeb's Home</title>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"60168\",secure:\"60173\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-20\" data-genuitec-path=\"/aaa/src/main/webapp/WEB-INF/views/adminPage/top/topIndex.jsp\">\r\n");
      out.write("<div style=\"background-color: white; opacity: 0.9; width: 1500px; height: 250px; left: 200px; top: 50px; position: relative; z-index: 1\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-20\" data-genuitec-path=\"/aaa/src/main/webapp/WEB-INF/views/adminPage/top/topIndex.jsp\">\r\n");
      out.write("<div class=\"topMid\">\r\n");
      out.write("\t<div class=\"bannerArea\" style=\"width:550px; height: 300px; top: 24px; left: -245px; position: absolute; z-index: 300\">\r\n");
      out.write("\t\t<a href=\"/aaa/\">\r\n");
      out.write("\t\t\t<img alt=\"\" src=\" /aaa/resources/img/yeob/5_White_logo_on_black_264x66.png\"\r\n");
      out.write("\t\t\t\tstyle=\"width:380px; height: 110px; background: ; position: absolute; z-index: 302;\"\r\n");
      out.write("\t\t\t\ttitle=\"홈으로 이동하기\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>  \r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t<div class=\"Total_Todays\" style=\"margin-left: 510px; margin-top: 55px;\" >\r\n");
      out.write("\t\t<div class=\"countbar\">\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    <div class=\"TotalHits\">Total Hits : </div>\r\n");
      out.write("\t\t\t<div class=\"counter\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ totalCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    <div class=\"TodaysHits\">Todays Hits : </div>\r\n");
      out.write("\t\t    <div class=\"counter\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ todaysCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- uio_auto_keyword -->\r\n");
      out.write("<div id=\"top_wrap\" style=\"position: relative; z-index: 500 ; margin-left: 0px; margin-top: 45px;\">\r\n");
      out.write("\t<div class=\"bg_top\" style=\"background-color: rgba(78,68,48,0.75);\"></div>\r\n");
      out.write("\t<!-- 탑메뉴 -->\r\n");
      out.write("\t\t<div class=\"top_menu\" style=\"color: black;\">\r\n");
      out.write("<!-- \t\t\t<h1><a href=\"/aaa/\"><img src=\"/aaa/resources/img/yeob/logo3.png\" alt=\"메인프로젝트 로고\"></a></h1> -->\r\n");
      out.write("\t\t\t<!-- gnb -->\r\n");
      out.write("\t\t<ul id=\"gnb\" class=\"gnb\">\r\n");
      out.write("\t\t\t<li class=\"menu menu_01\">\r\n");
      out.write("\t\t\t\t<div class=\"link\" style=\"cursor: default;\">전체보기</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub_menu sub_bg1\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a style=\"cursor:default;\">패션-뷰티</a>\r\n");
      out.write("\t\t\t\t\t\t<a style=\"cursor:default;\">식품</a>\r\n");
      out.write("\t\t\t\t\t\t<a style=\"cursor:default;\">생활-홈-데코</a>\r\n");
      out.write("\t\t\t\t\t\t<a style=\"cursor:default;\">가전-디지털</a>\r\n");
      out.write("\t\t\t\t\t\t<a style=\"cursor:default;\">지역</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"menu menu_02\">\r\n");
      out.write("\t\t\t\t<div class=\"link\" style=\"cursor: default;\">패션-뷰티</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub_menu sub_bg2\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"fashon_woman\">여성패션</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"fasion_man_uni\">남성·유니섹스패션</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"fasion_brand_woman\">여성브랜드패션</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"fasion_brand_man\">남성브랜드패션</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"fasion_sports\">스포츠패션</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"fasion_beauty\">뷰티</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"menu menu_03\">\r\n");
      out.write("\t\t\t\t<div class=\"link\" style=\"cursor: default;\">식품</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub_menu sub_bg3\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_fruit_vegetable\">과일·채소</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_sea_meat_egg\">수산·정육·계란</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_instant_processed\">즉석·가공식품</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_kimchi_sidedish_pastes\">김치·반찬·장류</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_snack\">스낵</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_drink\">음료</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_healthy_redginseng\">건강·홍삼</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_diet\">다이어트</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"food_imported\">수입식품</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"menu menu_06\">\r\n");
      out.write("\t\t\t\t<div class=\"link\" style=\"cursor: default;\">생활-홈-데코</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub_menu sub_bg4\">\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"sub_menu sub_bg4 sub1\"> -->\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"life_kitchen_dish\">주방용품·식기</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"life_detergent_cleanser\">세제·세안</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"life_storage_clean\">수납·정리</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"life_cleaning_product\">청소용품</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"life_wash_bath\">세탁·욕실용품</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"home_bedroom\">침실가구</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"home_living_storage\">거실·수납가구</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"home_kitchen\">주방가구</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"home_library_office\">서재·사무용가구</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"home_bedroom_curtain\">침실·커튼</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"deco_candle_diffuser\">캔들·디퓨저</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"deco_build_diy_landscape\">시공·DIY·조경</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"deco_interior\">홈·인테리어소품</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"menu menu_05\">\r\n");
      out.write("\t\t\t\t<div class=\"link\" style=\"cursor: default;\">가전-디지털</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub_menu sub_bg5\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"appliance_tv_refrigerator_washing\">TV·냉장고·세탁기</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"appliance_season\">계절가전</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"appliance_life\">생활가전</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"appliance_kitchen\">주방가전</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"appliance_car\">차량용디지털기기</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"digital_notbook_tablet_pc\">노트북·태블릿·PC</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"digital_game_software\">게임·소프트웨어</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"digital_storage_others\">저장장치·주변기기</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"digital_moniter_printer\">모니터·프린터</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"digital_mobile_acc\">모바일·액세서리</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"digital_camera_video_sound\">카메라·영상·음향</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"menu menu_04\">\r\n");
      out.write("\t\t\t\t<div class=\"link\" style=\"cursor: default;\">지역</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub_menu sub_bg6\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Gangnam\">강남</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_HongikUniv_Hapjeong_Sangsu\">홍대·합정·상수</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Myeongdong_Cityhall_Junggu\">명동·시청·중구</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Jamsill_Sincheon\">잠실·신천</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Seocho_Bangbae_Yangjae\">서초·방배·양재</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Daehangno_Suyu\">대학로·수유</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Apgujeong_Garosugil\">압구정·가로수</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Sinchon_EwhaUniv_Gongdeok\">신촌·이대·공덕</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Jongno_Gwanghwamun\">종로·광화문</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_songpa_Bangi_Garak\">송파·방이·가락</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Gangseo_Yangcheon\">강서·양천</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Nowon_Dobong\">노원·도봉</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Cheongdam_Hakdong_Nonhyeon\">청담·학동·논현</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Sangam_Eunpyeong\">상암·은평</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Itaewon_Hannam\">이태원·한남</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Gangdong_Cheonho_Gildong\">강동·천호·길동</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Gwanak_Dongjak_Sadang\">관악·동작·사당</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Seongdong_Dongdaemun\">성동·동대문</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Samseong_Yeoksam_Daechi\">삼성·역삼·대치</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Guro_Yeongdeungpo\">구로·영등포</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"loca_Konkuk_Guui_Jungnang\">건대·구의·중랑</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
